# Comparación de Entidades
Para incluir sólo una entidad, haz doble click sobre ella.
```{r compestados}
x <- "Nacional"
cat("\n\n")

cat(paste("## Gráfica Comparativa de Casos Activos \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.actcompstate[[x]], tooltip = "text",
                             dynamicTicks = TRUE)  %>%
                      layout(height = 720, legend = 
                              list(orientation = "h", y=-0.2) ))
cat("\n\n <div style='margin-bottom:350px;'> </div> \n\n")
    
cat(paste("## Gráfica Comparativa de Tasa de Incidencia según Casos Activos (por cada 100mil hab) \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.poscompstatetasa[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                      layout(height = 720, legend = 
                              list(orientation = "h", y=-0.2) )) 
cat("\n\n <div style='margin-bottom:350px;'> </div> \n\n")

cat(paste("## Gráfica Comparativa de Casos Positivos \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.poscompstate[[x]], tooltip = "text",
                             dynamicTicks = TRUE)  %>%
                      layout(height = 720, legend = 
                              list(orientation = "h", y=-0.2) ))
cat("\n\n <div style='margin-bottom:350px;'> </div> \n\n")
    
cat(paste("## Gráfica Comparativa de Tasa de Incidencia (por cada 100mil hab) \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.poscompstatetasa[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                      layout(height = 720, legend = 
                              list(orientation = "h", y=-0.2) )) 
cat("\n\n <div style='margin-bottom:350px;'> </div> \n\n")

cat(paste("## Gráfica Comparativa de Decesos \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.dececompstate[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                      layout(height = 720, legend = 
                              list(orientation = "h", y=-0.2) )) 
cat("\n\n <div style='margin-bottom:350px;'> </div> \n\n")

#cat(paste("## Gráfica Comparativa de Tasa de Decesos (por cada 100mil hab) \n\n"))
#cat("\n\n")
#htmltools::tagList( ggplotly(plot.dececompstate[[x]], tooltip = "text",
#                             dynamicTicks = TRUE) %>%
#                      layout(legend = list(orientation = "v"))) 

#cat("\n\n")

cat(paste("## Gráfica Comparativa de Casos Pendientes \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.pendcompstate[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                      layout(height = 720, legend = 
                              list(orientation = "h", y=-0.2) ))

cat("\n\n")

#cat(paste("## Gráfica Comparativa de Tasa de Casos Pendientes (por cada 100mil hab) \n\n"))
#cat("\n\n")
#htmltools::tagList( ggplotly(plot.pendcompstate[[x]], tooltip = "text",
#                             dynamicTicks = TRUE) %>%
#                      layout(legend = list(orientation = "v"))) 

cat("\n\n <div style='margin-bottom:350px;'> </div> \n\n")


```


# Nacional
```{r national}
x <- "Nacional"

cat(paste("## Resumen Actual de Casos en México \n \n"))
ktbl <- tbl.pais[[x]] %>%
          knitr::kable(format = "html",
                   digits = 0,
                   row.names = F,
                   align = "c") %>%
          kableExtra::kable_styling(
                  bootstrap_options = c("striped","condensed"),
                  full_width = F) 
  print(ktbl)

cat("\n\n")  


cat(paste("## Gráfica de Nuevos Casos \n\n"))
cat("Los casos positivos y pendientes son contabilizados respecto a la fecha de ingreso del caso. Los decesos son contabilizados respecta a la fecha de fallecimiento. **Importante**: los casos positivos son confirmados varios días después de que fueron infectados, lo cual significa que algunos de los casos pendientes actuales se 'convertirán' en casos positivos. \n\n")
htmltools::tagList( ggplotly(plot.casesnew[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v",
                                             x = 0)) )

cat("\n\n")

cat(paste("## Gráfica de Acumulado de Casos \n\n"))
cat("Los casos positivos y pendientes son contabilizados respecto a la fecha de ingreso del caso. Los decesos son contabilizados respecta a la fecha de fallecimiento. **Importante**: los casos positivos son confirmados varios días después de que fueron infectados, lo cual significa que algunos de los casos pendientes actuales se 'convertirán' en casos positivos. \n\n")
htmltools::tagList( ggplotly(plot.casestotal[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v",
                                             x = 0)) )

cat("\n\n")

cat(paste("## Gráfica de Casos Positivos por Edad/Sexo \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.possex[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) )

cat("\n\n")

cat(paste("## Gráfica de Decesos por Edad/Sexo \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.decesex[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) )

cat("\n\n")


cat(paste("## Gráfica de Hospitalizados por Edad/Sexo \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.hospitedadsex[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) )

cat("\n\n")


cat(paste("## Gráfica de Comorbilidades en Hospitalizados \n\n"))
cat(paste("De ", tbl.perchospcomorb[[x]][[1]], " casos positivos hospitalizados, ",
        tbl.perchospcomorb[[x]][[2]], " han presentado al menos una comorbilidad (", tbl.perchospcomorb[[x]][[3]], "%). \n\n",
        sep=""))
htmltools::tagList( ggplotly(plot.hospcomorb[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) )

cat("\n\n")


cat(paste("## Gráfica de Comorbilidades en Pacientes Intubados \n\n"))
cat(paste("De ", tbl.percintubcomorb[[x]][[1]], " casos positivos intubados, ",
        tbl.percintubcomorb[[x]][[2]], " han presentado al menos una comorbilidad (", tbl.percintubcomorb[[x]][[3]], "%). \n\n",
        sep=""))
htmltools::tagList( ggplotly(plot.intubcomorb[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) )

cat("\n\n")


cat(paste("## Gráfica de Casos Hospitalizados Intubados y/o en UCI \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.intub[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v")) )

cat("\n\n")


cat(paste("## Gráfica de Porcentaje Decesos Según Intubación \n\n"))
cat(paste("De ", tbl.percintub[[x]][[1]], " casos positivos hospitalizados, ",
        tbl.percintub[[x]][[2]], " han sido entubados (", tbl.percintub[[x]][[3]], "%). \n\n",
        sep=""))
htmltools::tagList( ggplotly(plot.intubdeath[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v")) )

cat("\n\n")


cat(paste("## Gráfica de Decesos por Enfermedad/Edad \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.condicion[[x]], tooltip = "text") %>%
                      layout(height = 750))

cat("&nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n")

cat(paste("## Gráfica de Porcentaje de Decesos según Número de Comorbilidades \n\n"))
cat("Esta gráfica considera el porcentaje de decesos que han occurido respecto al número de comorbilidades en cada paciente. Sólo se consideran casos positivos que han sido hospitalizados. \n\n")
htmltools::tagList( ggplotly(plot.comorbdeath[[x]], tooltip = "text",
                             dynamicTicks = TRUE))

cat("\n\n")


cat(paste("## Gráfica de Inicio de Sintomas y Deceso \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.time2death[[x]], tooltip = "text",
                             dynamicTicks = TRUE))

cat("\n\n")

cat(paste("## Gráfica de Casos/Pruebas por Fecha de Ingreso  \n\n"))
cat("El número de casos/pruebas está calculado como la suma de casos Positivos, No Positivos y Pendientes por Fecha de Ingreso de los casos.  \n\n")
htmltools::tagList( ggplotly(plot.pruebasnew[[x]], tooltip = "text",
                             dynamicTicks = TRUE) )

cat("\n\n")

cat(paste("## Gráfica de Tasa de Positividad y Letalidad \n\n"))
cat("La tasa de Positividad al día d está calculada de acuerdo a la fórmula 
    $$ \\text{Tasa Positividad al día d} = \\frac{\\text{casos positivos al día d}}{\\text{casos positivos al día d + casos no positivos al día d}}.$$
    La tasa de Letalidad al día d está calculada de acuerdo a la fórmula 
    $$ \\text{Tasa Letalidad al día d} = \\frac{\\text{decesos al día d}}{\\text{casos positivos al día d}}.$$ 
    **Importante:** dado que los casos positivos son obtenidos mediante un muestreo de la población de casos sospechosos, la tasa de letalidad es en realidad menor a la calculada. \n\n")
htmltools::tagList( ggplotly(plot.tasatotal[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v",
                                             x = 0)) )

cat("\n\n")

cat(paste("## Casos por Entidad de Residencia \n \n"))
ktbl <- tbl.entidades[[x]] %>% 
          arrange(desc(`Positivo`)) %>%
          knitr::kable(format = "html",
                   digits = 0,
                   row.names = F,
                   align = "c") %>%
          kableExtra::kable_styling(
                  bootstrap_options = c("striped","condensed"),
                  full_width = F) %>%
          kableExtra::scroll_box(height = "280px")
  print(ktbl)

cat("\n\n")  

cat(paste("## Gráfica por Institución que Brindó la Atención \n\n"))
cat("\n\n")
htmltools::tagList( ggplotly(plot.sector[[x]], tooltip = "text",
                             dynamicTicks = TRUE) )

cat("\n\n")

```

```{r state}
grp_names_state <- grp_names[grp_names != "Nacional"]
for(x in grp_names_state){
  
  cat(paste("#", x, sep = " ", "\n\n"))

  cat(paste("## Resumen Actual de Casos \n\n", sep = " "))
  ktbl <- tbl.entidades[["Nacional"]] %>% 
              filter(`Entidad Residencia` == x) %>%
              select(-c(`Entidad Residencia`)) %>%
          knitr::kable(format = "html",
                   digits = 0,
                   row.names = F,
                   align = "c") %>%
          kableExtra::kable_styling(
                  bootstrap_options = c("striped","condensed"),
                  full_width = F)
    print(ktbl)

  cat("\n\n")    
  cat(paste("## Gráfica de Nuevos Casos \n\n"))
  cat("Los casos positivos y pendientes son contabilizados respecto a la fecha de ingreso del caso. Los decesos son contabilizados respecta a la fecha de fallecimiento. **Importante**: los casos positivos son confirmados varios días después de que fueron infectados, lo cual significa que algunos de los casos pendientes actuales se 'convertirán' en casos positivos. \n\n")

  print(htmltools::tagList( ggplotly(plot.casesnew[[x]], tooltip = "text",
                                     dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) ))
  
  cat("## Gráfica de Acumulado de Casos \n\n")
  cat("Los casos positivos y pendientes son contabilizados respecto a la fecha de ingreso del caso. Los decesos son contabilizados respecta a la fecha de fallecimiento. **Importante**: los casos positivos son confirmados varios días después de que fueron infectados, lo cual significa que algunos de los casos pendientes actuales se 'convertirán' en casos positivos. \n\n")
  print(htmltools::tagList( ggplotly(plot.casestotal[[x]], tooltip = "text",
                                     dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) ))
  
  cat(paste("## Gráfica de Casos Positivos por Edad/Sexo \n\n"))
  cat("\n\n")
  print(htmltools::tagList( ggplotly(plot.possex[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) ))
  
  cat(paste("## Gráfica de Decesos por Edad/Sexo \n\n"))
  cat("\n\n")
  print(htmltools::tagList( ggplotly(plot.decesex[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) ))
  
  cat(paste("## Gráfica de Hospitalizados por Edad/Sexo \n\n"))
  cat("\n\n")
  print(htmltools::tagList( ggplotly(plot.hospitedadsex[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) ) )

  cat("\n\n")

  cat(paste("## Gráfica de Comorbilidades en Hospitalizados \n\n"))
  cat(paste("De ", tbl.perchospcomorb[[x]][[1]], " casos positivos hospitalizados, ",
        tbl.perchospcomorb[[x]][[2]], " han presentado al menos una comorbilidad (",
        tbl.perchospcomorb[[x]][[3]], "%). \n\n",
        sep=""))
  print(htmltools::tagList( ggplotly(plot.hospcomorb[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) ))

  cat("\n\n")

  cat(paste("## Gráfica de Comorbilidades en Pacientes Intubados \n\n"))
  cat(paste("De ", tbl.percintubcomorb[[x]][[1]], " casos positivos intubados, ",
        tbl.percintubcomorb[[x]][[2]], " han presentado al menos una comorbilidad (",
        tbl.percintubcomorb[[x]][[3]], "%). \n\n",
        sep=""))
  print(htmltools::tagList( ggplotly(plot.intubcomorb[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) ))

  cat("\n\n")
  
  cat(paste("## Gráfica de Casos Hospitalizados Intubados y/o en UCI \n\n"))
  cat("\n\n")
  print(htmltools::tagList( ggplotly(plot.intub[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v")) ))
  
  cat(paste("## Gráfica de Porcentaje Decesos Según Intubación \n\n"))
  cat(paste("De ", tbl.percintub[[x]][[1]], " casos positivos hospitalizados, ",
        tbl.percintub[[x]][[2]], " han sido entubados (", tbl.percintub[[x]][[3]], "%). \n\n",
        sep=""))
  print(htmltools::tagList( ggplotly(plot.intubdeath[[x]], tooltip = "text",
                             dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v")) ))
  
  cat(paste("## Gráfica de Decesos por Enfermedad/Edad \n\n"))
  cat("\n\n")
  print(htmltools::tagList( ggplotly(plot.condicion[[x]], tooltip = "text") %>%
                      layout(height = 750)))
  
cat("&nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n
    &nbsp; \n\n")

  cat(paste("## Gráfica de Porcentaje de Decesos según Número de Comorbilidades  \n\n"))
  cat("Esta gráfica considera el porcentaje de decesos que han occurido respecto al número de comorbilidades en cada paciente. Sólo se consideran casos positivos que han sido hospitalizados. \n\n")
  print(htmltools::tagList( ggplotly(plot.comorbdeath[[x]], tooltip = "text",
                             dynamicTicks = TRUE)))

  cat(paste("## Gráfica de Inicio de Sintomas y Deceso \n\n"))
  cat("\n\n")
  print(htmltools::tagList( ggplotly(plot.time2death[[x]], tooltip = "text",
                             dynamicTicks = TRUE)))

  cat(paste("## Gráfica de Casos/Pruebas por Fecha de Ingreso  \n\n"))
  cat("El número de casos/pruebas está calculado como la suma de casos Positivos, No Positivos y Pendientes por Fecha de Ingreso de los casos.  \n\n")
  print(htmltools::tagList( ggplotly(plot.pruebasnew[[x]], tooltip = "text",
                             dynamicTicks = TRUE) ) )
  
  cat("## Gráfica de Tasa Positividad y Letalidad \n\n")
  cat("La tasa de Positividad al día d está calculada de acuerdo a la fórmula 
    $$ \\text{Tasa Positividad al día d} = \\frac{\\text{casos positivos al día d}}{\\text{casos positivos al día d + casos no positivos al día d}}.$$
    La tasa de Letalidad al día d está calculada de acuerdo a la fórmula 
    $$ \\text{Tasa Letalidad al día d} = \\frac{\\text{decesos al día d}}{\\text{casos positivos al día d}}.$$ 
    **Importante:** dado que los casos positivos son obtenidos mediante un muestreo de la población de casos sospechosos, la tasa de letalidad es en realidad menor a la calculada. \n\n")
  print(htmltools::tagList( ggplotly(plot.tasatotal[[x]], tooltip = "text",
                                     dynamicTicks = TRUE) %>%
                        layout(legend = list(orientation = "v", x = 0)) )) 
  
  cat(paste("## Casos por Municipio de Residencia \n \n"))
  ktbl <- tbl.municipios[[x]] %>% 
              arrange(desc(`Positivo`)) %>%
    knitr::kable(format = "html",
                  digits = 0,
                 row.names = F,
                 align = "c") %>%
    kableExtra::kable_styling(
          bootstrap_options = c("striped","condensed"),
          full_width = F) %>%
    kableExtra::scroll_box(height = "280px")
  print(ktbl)
  
  cat(paste("## Gráfica por Institución que Brindó la Atención \n\n"))
  cat("\n\n")
  print(htmltools::tagList( ggplotly(plot.sector[[x]], tooltip = "text",
                             dynamicTicks = TRUE) ))
  
  cat("\n\n")
}
```


